### ISSUE TITLE
If WebCrypto invocation fails (it throws NotSupported) do not show the “Any” section

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/csrhelp#1]
The Any section generates a PKCS#10 and private key but will only work when WebCrypto is available.

For example if you try to invoice the page over HTTP you will get an alert() saying it failed to invoke WebCrypto. It should not do this and instead it should just not show this section:

![image](https://cloud.githubusercontent.com/assets/1619279/11787180/3a33d7e2-a23f-11e5-9050-5164a067870d.png)

But you should not since when you call generate key you get NotSupportedError. You should probably call generate key before you show the “Any” result, then only show it if you do not get the NotSupported Error.

Also some browsers also don’t support ECC (Microsoft Edge for example) so catching this and hiding Any would make the page work well in these cases.

**Comment by rmhrisk** [comment]
Open the page in Safari, enter host name, choose ECC. You will see a repro

**Comment by somnath-kokane** [comment]
:shipit: 
when generate  PKCS#10 and private key fails, it won't show an error. "any" section would be hidden
