### ISSUE TITLE
In firefox there is no whitespace around boxes

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/csrhelp#20]
In firefox there is no whitespace around boxes:

![image](https://cloud.githubusercontent.com/assets/1619279/11805302/7dea5936-a2bf-11e5-92dd-f08cafa3b4da.png)

vs:

![image](https://cloud.githubusercontent.com/assets/1619279/11805309/8929f6da-a2bf-11e5-812f-4cbf46c5e273.png)

**Comment by somnath-kokane** [comment]
:shipit: 

css issue - resolved
