### ISSUE TITLE
No progress bar when generating keys

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/csrhelp#23]
Previously there was a progress bar when generating keys, it is gone now:

![image](https://cloud.githubusercontent.com/assets/1619279/11816427/44981f9c-a305-11e5-82ec-a64617dd2055.png)

Key gen can take a while we need the progress bar so people know something is happening. Look at 8092bit key gen as an example.

**Comment by somnath-kokane** [comment]
:+1: 

done
