### ISSUE TITLE
Layout issues on mobile

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/csrhelp#27]
![image](https://cloud.githubusercontent.com/assets/1619279/11827806/eeafe58a-a343-11e5-9269-c8d4709c1d3a.png)
![image](https://cloud.githubusercontent.com/assets/1619279/11827807/eecbad9c-a343-11e5-8977-11bd0ff873e4.png)

**Comment by somnath-kokane** [comment]
:+1: 

done
