### ISSUE TITLE
When no match in Open Corporates do not show empty box

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/csrhelp#29]
![image](https://cloud.githubusercontent.com/assets/1619279/11926052/456b0068-a776-11e5-9cfd-e85fa4632ad4.png)

**Comment by rmhrisk** [comment]
How certsimple deals with this is by having the text box progressivly add what is typed:
![image](https://cloud.githubusercontent.com/assets/1619279/11927716/6c4ca1a2-a783-11e5-9171-294be87e583c.png)

**Comment by rmhrisk** [comment]
Not saying we need to do the same thing, simply not showing an empty box might be enough.

**Comment by somnath-kokane** [comment]
:+1: 
done
