### ISSUE TITLE
Set location based on Open Corporates selection

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/csrhelp#31]
When user chooses an Open Corporates match we should set the location based on the selected Jurisdiction.

For example we would look at item.company.jurisdiction_code to get this, for this record
[http://api.opencorporates.com/companies/us_wa/603409910]

We would need to go from the jurisdiction code to the right name:

```
"jurisdiction_code": "us_wa",
```

'''The jurisdiction code is the code for the jurisdiction which registered the company. If this is a country it is simply the two-letter ISO code for that country, e.g. Spain = es, United Kingdom = gb. If this is a state or province it is an underscore version of the ISO 3166-2 code for the jurisdiction, eg. Michigan in the US is us_mi.'''

If the user selects the open corporate org then we should clear the location data we do not have also. Otherwise we may create conflicts when the request is recieved by the CA. Basically if Open Corporates is used we should only use it.

But this would ensure the CSR has the right combination of information.

**Comment by rmhrisk** [comment]
JSON with country two letter country code - https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes/blob/master/slim-2/slim-2.json

JSON with US jurisdiction - https://gist.github.com/HarishChaudhari/9465648

**Comment by somnath-kokane** [comment]
:+1: 
done

{"error":{"message":"Rate Limit Exceeded"}} getting this error after few requests done.

**Comment by rmhrisk** [comment]
We may need to get our own API key and setup a node proxy to use this without the rate limit error. I will do some investigation.
