### ISSUE TITLE
P-521 CSR verification

### ISSUE THREAD

**Issue by l-ko** [PeculiarVentures/csrhelp#36]
I've used this example https://pkijs.org/examples/PKCS10_complex_example.html to verify the CSR generated by https://csrhelp.peculiarventures.com/
Some generated P-521 CSRs return true, but some false for some reason.

**Comment by YuryStrozhevsky** [comment]
There is a problem in PKIjs, see [this issue](https://github.com/GlobalSign/PKI.js/issues/64).

**Comment by YuryStrozhevsky** [comment]
CSRHELP project must update PKIjs source from latest commit.

**Comment by YuryStrozhevsky** [comment]
I have updated the project's files.
