### ISSUE TITLE
Do not generate new command lines on domain validation.

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/csrhelp#4]
Right now each time you type a character in the hostname field it checks to see if it is a valid domain or not, if it is a new command line example is generated. This is OK for the “command line” examples but the “Any” example can take a few seconds to work because some browsers (firefox) do not generate keys asynchronously.

To address this we need to make the hostname field work like the other fields. In other words, new command lines (and the ANY example) should only be generated when all required fields have been completed and one of the fields lose focus.

**Comment by somnath-kokane** [comment]
:+1: 

done
