### ISSUE TITLE
When generating a new command lines we must clear the prior command lines first.

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/csrhelp#5]
Imagine the case where you fill out the form and it generates you a set of results, you now decide to go change the results. Since some results (specifically the Any result) can take a few seconds to be generated with the new options we need to disable all the results before calculating the new values. Otherwise the user may see data in the “form” that is inconsistent with the “results”.

The easiest way to see this is while in Firefox, fill out the form once, set the RSA key size to 8092 and see it can take seconds for the new ANY value to be populated.

**Comment by somnath-kokane** [comment]
:+1: 

done

**Comment by rmhrisk** [comment]
Think this was not done right. Steps to reproduce:
1. Visit page
2. Enter hostname
3. Exit hostname field
4. See ANY result 
5. Change keysize to 8092
6. Wait
7. Observe that the form shows 8092 but the CSR is "small" and 2048.
8. Observe once keygen happens all results go away
9. Observe once keygen happens ANY result is correct.

Instead of the above on field exit:
1. Generate commands
2. Clear result box for any so it is just empty row with no CSR, no download button, no copy button.
3. Turn on progress bar
4. Once keygen complete disable progress bar
5. Once keygen complete show CSR, show download and copy buttons

**Comment by somnath-kokane** [comment]
:+1: 

done
