### ISSUE TITLE
Check in each of the third-party dependencies into the repository and reference them in the CSS, JS and HTML.

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/csrhelp#8]
Since this page generates cryptographic keys, we do not want this web page to take dependencies on third-party hosted content. This content would have a chance of influencing the key generation process.

Right now the page includes a reference to fonts hosted out of the repository, I don’t think there are more but you need to review the dependencies and make sure they reference files that are part of the project (e.g. check in the fonts).

**Comment by somnath-kokane** [comment]
:shipit: 

checked in this repository
